### ISSUE TITLE
MQTT seems to lose connection with broker?

### ISSUE THREAD

**Issue by elisavisio** [Orange-OpenSource/LiveObjects-samples-nodejs#1]
The package.json installs the MQTT package v1.1 .
With this version, MQTT client seems to lose connection with broker after few minutes even if the status answers always connected.
I have the problem on two different hosting.
I have update the package.json to install a version above 2.0 and now the connection stays active.

**Comment by boly38** [comment]
Hi @elisavisio,
(sorry for long delay)

`package.json` defines mqtt `^1.10` which results _today_ in `1.14` (not 1.1).

I were unable to reproduce your issue which seems outdated today.
Feel free to reopen it if it's not fixed for you.
